# Órdenes para leer los microdatos
library(tidyverse)
naccomp.2018 <- read.fwf(file = "NACIMI.ANONIMI.A2018.ESTPR.txt",
  widths=c(2,3,2,4,2,3,1,1,1,1,1,1,2,2,4,1,1,3,1,2,3,3,2,3,3,2,2,1,1,2,4,1,1,2,4,2,2,2,4,2,3,3,1,1,3,2,4,1,1,3,1,2,3,3,1,2,3,3,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,3,3,2,1,1,3,1,4,1,1,1,1,1,2,1,1,2,2,1,1,1,15),
  col.names = c("PROI","MUNI","MESPAR","ANOPAR","PROPAR","MUNPAR","LUGARPA","ASISTIDO","MULTIPLI","NORMA","CESAREA","INTERSEM","SEMANAS","MESNACM","AÑONACM","NACIOEM","NACIOXM","PAISNACM","CUANNACM","PROMA","MUNMA","PAISNXM","PROREM","MUNREM","PAISRXM","ESTUDIOM","CAUTOM","ECIVM","CASPNM","MESMAT","AÑOMAT","PHECHO","ESTABLE1","MESEST1","AÑOEST1","NUMH","NUMHV","MESHAN","AÑOHAN","PROHANTE","MUNHANTE","PAISHANTX","NACIOEHA","NACIOXHA","PAISNAHA","MESNACP","AÑONACP","NACIOEP","NACIOXP","PAISNACP","CUANNACP","PROPA","MUNPA","PAISNXP","DONDEP","PROREP","MUNREP","PAISRXP","ESTUDIOP","CAUTOP","TMUNIN","TMUNNM","TMUNNP","TMUNNHA","TMUNRM","TMUNRP","TPAISNACIMIENTOMADRE","TPAISNACIMIENTOPADRE","TPAISNACIMIENTOHIJOANTE","TPAISRMADRE","TPAISRPADRE","TPAISNACIONALIDADMADRE","TPAISNACIONALIDADPADRE","TPAISNACIONALIDADHIJOANT","TPAISNACIONALIDADNACIDO","EDADM","EDADMM","EDADMREL","ANOCA","ANOREL","INIHA","BLANCOS","EDADP","NACIOEN","NACIOXN","PAISNACN","SEXO","PESON","V24HN","NACVN","AUTOPSN","MUERN","CODCA1N","CODCA2N","CODCA4N","CLASIF","SORDENV","NUMHVT","TMUNPAR","RELAM","RELAP","BLANCO"),
)
# Ojo: tarda mucho en leer el fichero completo
# Elegir solamente las variables más importantes
nacabrv.2018 <- read.fwf(file = "NACIMI.ANONIMI.A2018.ESTPR.txt",
                         widths=c(2,3,2,4,-6,1,1,1,1,1,2,-28,2,2,1,-67,2,2,-38,1,4,1,1,1,1,1,2,1,1,2,2,-18),
                         col.names = c("PROI","MUNI","MESPAR","ANOPAR","ASISTIDO","MULTIPLI","NORMA","CESAREA","INTERSEM","SEMANAS","ESTUDIOM","CAUTOM","ECIVM","ESTUDIOP","CAUTOP","SEXO","PESON","V24HN","NACVN","AUTOPSN","MUERN","CODCA1N","CODCA2N","CODCA4N","CLASIF","SORDENV","NUMHVT")
)
# Eliminamos variables con valores perdidos o vacías
nacabrv.2018 <- nacabrv.2018 %>% 
  select(-c(MUNI,ANOPAR,AUTOPSN,CODCA1N,CODCA2N,CODCA4N))
str(nacabrv.2018)
mean(is.na(nacabrv.2018$PESON))
summary(nacabrv.2018)
ggplot(data=nacabrv.2018,aes(PESON)) +
  geom_histogram()