---
title: "Dibuja la recta"
output:
  beamer_presentation: default
  powerpoint_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Diagrama 1
```{r datos1}
x1 <- c(1,2,3)
y1 <- c(1,2,3)
```

```{r diagrama1}
plot(x1,y1, xlim=c(0,4), ylim=c(0,4), pch=16)
```

---

```{r diagrama1b}
plot(x1,y1, xlim=c(0,4), ylim=c(0,4), pch=16)
abline(lm(y1 ~ x1), col="RED")
```

## Diagrama 2

```{r}
x2 <- c(1,1,2)
y2 <- c(1,2,2)
```

```{r diagrama2}
plot(x2,y2, xlim=c(0,4), ylim=c(0,4), pch=16)
```

---

```{r diagrama2b}
plot(x2,y2, xlim=c(0,4), ylim=c(0,4), pch=16)
abline(lm(y2 ~ x2), col="RED")
```

## Diagrama 3

```{r}
x3 <- c(1,1,2,2)
y3 <- c(1,2,1,2)
```

```{r diagrama3}
plot(x3,y3, xlim=c(0,4), ylim=c(0,4), pch=16)
```

---

```{r diagrama3b}
plot(x3,y3, xlim=c(0,4), ylim=c(0,4), pch=16)
abline(lm(y3 ~ x3), col="RED")
```

## Diagrama 4

```{r datos4}
x4 <- c(1,2,3,3,4,5)
y4 <- c(2,3,1,3,2,3)
```

```{r diagrama4}
plot(x4,y4, xlim=c(0,6), ylim=c(0,4), pch=16)
```

---

```{r diagrama4b}
plot(x4,y4, xlim=c(0,6), ylim=c(0,4), pch=16)
abline(lm(y4 ~ x4), col="RED")
```


