---
title: "Regresión y correlación"
output: html_notebook
---

```{r configuracion, echo=FALSE}
library(MASS)
library(ggplot2)
```

Este documento se basa en el contenido de un post, publicado en *R bloggers*. Reemplazo los "=" por "<-"

```{r genera datos, echo=FALSE}
corrdata <- function(samples=200,r=0){
  data <-  mvrnorm(n=samples, mu=c(0, 0), Sigma=matrix(c(1, r, r, 1), nrow=2), empirical=TRUE)
  X <-  data[, 1]  # standard normal (mu=0, sd=1)
  Y <-  data[, 2]  # standard normal (mu=0, sd=1)
  data.frame(x=X,y=Y)
}
 
df=data.frame()
for (i in c(1,0.8,0.5,0.2,0,-0.2,-0.5,-0.8,-1)){
  tmp <- corrdata(200,i)
  tmp['corr'] <- i
  df <- rbind(df,tmp)
}
```

Y ahora representamos los gráficos:
```{r diagramas1, echo=FALSE}
g <- ggplot(df,aes(x=x,y=y))+geom_point(size=1)
g+facet_wrap(~corr)+ stat_smooth(method='lm',se=FALSE,color='red')
```
Para mejorar la presentación, y que las gráficas tengan los mismos ejes, añado la orden `+ coord_fixed()`

```{r}
g +
  facet_wrap(~corr) +
  stat_smooth(method='lm',se=FALSE,color='red')+ 
  coord_fixed()
```

