---
title: "La paradoja del cumpleaños"
output: html_notebook
---

```{r echo=FALSE }
library(tidyverse)
theme_set(theme_light())
```
La fuente de este [comentario](https://www.r-bloggers.com/the-birthday-paradox-puzzle-tidy-simulation-in-r/) se publicó en R-Bloggers.  

La paradoja del cumpleaños se usa en muchos cursos de estadística para discutir sobre la probabilidad.  
Veamos en primer lugar cómo se simula una sala con 50 personas.

```{r}
summarized <- crossing(people = seq(2, 50, 2),
                       trial = 1:10000) %>%
  mutate(birthday = map(people, ~ sample(365, ., replace = TRUE)),
         multiple = map_lgl(birthday, ~ any(duplicated(.)))) %>%
  group_by(people) %>%
  summarize(chance = mean(multiple))
```

Y ahora representemos los valores de la probabilidad
```{r}
# Visualizing the probability
ggplot(summarized, aes(people, chance)) +
  geom_line() +
  scale_y_continuous(labels = scales::percent_format()) +
  labs(y = "Probability two have the same birthday")
```

