---
title: "Comparación de medias de dos grupos"
output:
  powerpoint_presentation: null
  slide_level: 2
  beamer_presentation: default
---

```{r configura, echo=F}
library(ggplot2)
load("~/material_docente/testhipotesis/pies_1920.RData")
```

## ¿Son diferentes?

Respecto a su estructura corporal  

---

```{r, echo=FALSE}
boxplot(IMC~sexo, ylab="IMC", xlab="sexo", data=pies_1920)
```

## ¿Son diferentes? (2)

Con respecto a las características de sus pies   

---

```{r, echo=FALSE}
boxplot(longitud.pie~sexo, ylab="Longitud pie", xlab="sexo", data=pies_1920)
```

## ¿Son diferentes? (2)

```{r, echo=FALSE}
boxplot(ancho.pie~sexo, ylab="Ancho pie", xlab="sexo", data=pies_1920)
```

## Hipótesis nula

$$H_0: \mu_{A} = \mu_{B}$$


$$H_0: \mu_{A}-\mu_{B}=0$$

---

```{r h0, echo=F, warning=FALSE}
t1 <- ggplot(data.frame(x = c(-4, 4)), aes(x = x)) +
      stat_function(fun = dt, args = list(df = 20)) +
      geom_vline(xintercept = 0, colour="red", size=1,5) +
      scale_x_continuous(breaks=0) +
      xlab(NULL) +
      theme_bw()
t1
```


## Hipótesis alternativa

$$H_1: \mu_{A} \neq \mu_{B}$$  

$$H_1:\mu_{A} - \mu_{B} \neq 0$$

---

```{r h1, echo=F}
t2 <- ggplot(data.frame(x = c(-4, 4)), aes(x = x)) +
      stat_function(fun = dt, args = list(x=-1,df = 20)) +
      stat_function(fun = dt, args = list(x=+1,df = 20)) +
      geom_vline(xintercept = c(-1,1), color="red") +
      scale_x_continuous(breaks=c(-1,1), labels=c("A","B")) +
      xlab(NULL) +
      theme_bw()
t2
```

## Estadístico del test

$$t_{exp} = \frac{\bar{x}_A - \bar{x}_B}{E.T.(\bar{x}_A - \bar{x}_B)} $$  

$$t_{exp} = \frac{\bar{x}_A - \bar{x}_B}{\sqrt{s_A/n_A - s_B/n_B}} $$ 


## Orden de R

```{r eval=F}
t.test(ancho.pie~sexo, alternative='two.sided', conf.level=.95, var.equal=TRUE, 
  data=pies_1920)
```

## Resultado del test bilateral

```{r, echo=F}
test1 <- t.test(ancho.pie~sexo, alternative='two.sided', conf.level=.95, var.equal=TRUE, 
  data=pies_1920)
test1
```

---

```{r, echo=F}
funcShaded <- function(x) {
    y <- dt(x, df=20)
    y[x > qt(0.025,20) & x < qt(0.975,20)] <- NA
    return(y)
}
t3 <- ggplot(data.frame(x = c(-4, 4)), aes(x = x)) +
      stat_function(fun = dt, args = list(df = 20)) +
      stat_function(fun=funcShaded, geom="area", fill="red") +
  geom_vline(xintercept = test1$statistic, color="navy") +
      scale_x_continuous(breaks=0) +
      xlab(NULL) +
      theme_bw()
t3
```

## Resultado del test unilateral

```{r, echo=F}
t.test(ancho.pie~sexo, alternative='less', conf.level=.95, var.equal=FALSE, 
  data=pies_1920)
```

---

```{r, echo=F}
test2 <- t.test(ancho.pie~sexo, alternative='less', conf.level=.95, var.equal=FALSE, 
  data=pies_1920)

funcShaded <- function(x) {
    y <- dt(x, df=20)
    y[x > qt(0.05,20)] <- NA
    return(y)
}
t4 <- ggplot(data.frame(x = c(-4, 4)), aes(x = x)) +
      stat_function(fun = dt, args = list(df = 20)) +
      stat_function(fun=funcShaded, geom="area", fill="red") +
      geom_vline(xintercept = test2$statistic, color="navy") +
      scale_x_continuous(breaks=0) +
      xlab(NULL) +
      theme_bw()
t4
```
